#!/bin/bash
set -e

usage() {
  echo "usage: $0 [-b build & start] [-s stop] [-r restart] [-d delete] [-dev run dev]"
  exit 1
}

if [ $# -ne 1 ]; then
  usage
fi

case "$1" in
  -b)
    docker compose build --no-cache
    docker compose up -d
    ;;
  -dev)
    npm run dev
    ;;
  -s)
    docker compose stop
    ;;
  -r)
    docker compose restart
    ;;
  -d)
    docker compose down --rmi all
    ;;
  *)
    usage
    ;;
esac
